= ThoughtSpot REST APIs
:toc: true

:page-title: ThoughtSpot REST APIs
:page-pageid: rest-apis
:page-description: ThoughtSpot REST API provides service endpoints for administration, embedding, and data management.

The ThoughtSpot REST API framework lets you create, access, edit, and manage objects and resources in the ThoughtSpot system programmatically. 
 
ThoughtSpot REST API supports several resource collections and operations in two distinct versions: 

* REST API v1
+
The legacy framework with several endpoints to create, edit, administer and manage ThoughtSpot objects and data. 

* REST API v2.0
+
The REST API v2.0 framework provides enhanced functionality and improved API experience with an interactive Playground.

For more information about the differences between these two REST API versions, see xref:rest-api-v1v2-comparison.adoc[REST API v1 and v2.0 comparison].

== REST API Playground

ThoughtSpot users with Developer or Administrator privileges can access the REST API v1 and v2.0 endpoints in the *Develop* tab. The portal provides a separate Playground for each REST API version and lets you explore the API endpoints, request and response workflows.

* To try out the xref:rest-api-v1.adoc[REST API v1 endpoints], click **REST Playground v1**. +
* To access the xref:rest-api-v2.adoc[REST API v2 Playground], click **REST Playground v2**.

==  API endpoints
For a complete list of API endpoints and information about how to make an API call to these endpoints, see the following reference pages:

* xref:rest-api-reference.adoc[REST API v1 Reference]
* xref:rest-api-v2-reference.adoc[REST API v2.0 Reference]

== Certificate requirements for REST API requests via HTTPS

To communicate and exchange data with a ThoughtSpot application server securely via HTTPS:

. SSL must be configured on your ThoughtSpot application instance
+
In production environments, ThoughtSpot recommends using HTTPS with valid SSL certificates issued by a trusted Certificate Authority (CA).
+
For example, if you are using Postman to make API calls, your API requests return `SSL Error: Self signed certificate` error if your endpoint uses a certificate that's registered with an internal certificate registry. Postman allows you to link:https://learning.postman.com/docs/sending-requests/certificates/[add the trusted CA certificate, window=_blank] or turn off SSL verification.

. Your REST client must have access to the server certificate in the Keystore or Truststore on your  client environment.
+
One of the common causes for certificate errors during a REST API operation is the non-availability of trusted SSL certificates in the Keystore or Truststore on your client environment. For example, in a JDK-based implementation, the trusted certificates and required keys must be available in the Java Keystore of your client application. Similarly, for Python-based implementations, the SSL certificates must be available in the certificate store used by Python.

+
In some cases, your application may require a certificate chain that contains a sequence of certificates, including the root and intermediate certificates. In a development or testing environment, you can choose to skip the SSL certificate verification step. However, in production environments, ThoughtSpot recommends using the SSL verification checks to ensure that your REST client uses trusted server certificates when calling REST APIs.

+
If you don't have the server certificate on your client environment, try exporting the SSL certificate from your ThoughtSpot application server via a Web browser. For example, to export an SSL certificate or certificate chain via Chrome, follow these steps:

.. Click the locked icon in the URL and navigate to the *Details* tab to view the certificates issued for your application instance.
.. Select the certificates in the certificate hierarchy.
.. Click *Export*.

+
For information about how to import the root and intermediate certificates into Truststore or Keystore on your client environment, refer to the following resources:

* For Java applications, see link:https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html[https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html, window=_blank] and link:https://docs.oracle.com/javaee/5/tutorial/doc/bnbxw.html[https://docs.oracle.com/javaee/5/tutorial/doc/bnbxw.html, window=_blank]. +
* For Python clients, see link:https://docs.python.org/3/library/ssl.html#certificates[ttps://docs.python.org/3/library/ssl.html#certificates, window=_blank].
