= Runtime parameter overrides
:toc: true
:toclevels: 2

:page-title: Runtime parameters
:page-pageid: runtime-parameters
:page-description: Use parameters to run multiple scenarios with adjustable values, without changing your answer.

A parameter in ThoughtSpot refers to a placeholder number, date, or string that can replace a constant value in the data source objects. Parameters to a Worksheet, saved, or Liveboard to optimize your queries and run different scenarios with adjustable values, without creating or modifying the constants in formulas for each new value.

You create parameters in a Worksheet and then integrate them into formulas, filters, search, and Liveboards. The analyst and end business user must be able to easily set the parameters, and the setting of a parameter must cause the dependent visualization(s) to update.

Parameters are useful for 'what-if' analysis, financial planning, cohort analysis, and so on. When you create parameters for your Worksheets, you guide users in their exploration of the data as they search on your Worksheets. When you create parameters for your Answers, you empower yourself and other viewers of your Answers to run scenarios on the data in the Answer, using adjustable values.

== Using parameters
<Add reference to main docs>

== Runtime parameter overrides

You can adjust parameter values at runtime from Liveboard or Answer URLs, or using REST API v1 requests.

=== URL parameters

=== Parameter overrides in REST API

<TBD>

=== Runtime filters in REST API calls

To add a runtime filter to your API call or the embedded object:

. Construct the URL for embedding the visualization or making a REST API call.
. Paste the URL into a text editor.
. Append the runtime filter to the URL, using the runtime filter operators.

The URL format for applying runtime filters to a Liveboard in a REST API call is:

----
http://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/pinboarddata?id=<Liveboard_id>&param1=Discount&paramVal1=0.25
----

The URL format for applying runtime filters to a Liveboard visualization in a REST API call is:

----
http://{ThoughtSpot-Host}/callosum/v1/tspublic/v1/pinboarddata?id=<Liveboard_id>&vizid=%5B<visualization_id>%5D&&param1={parameter}&paramVal1={Parameter_Value}
----

==== Add additional filters

////
You can add additional filters by incrementing the number at the end of each parameter in the runtime filter for each filter you add, for example, col2, op2, val2, and so on. To add additional filters on a particular column, you can specify multiple values by separating them with an ampersand (&) as shown in the example here:

----
val1=foo&val1=bar
----

You can also use the `IN` operator for multiple values, as shown in this example:

----
col1=<column_name>&op1=IN&val1=<value>&val1=<value>
----

The following example passes multiple variables to a single column as well as multiple columns. It shows that the data values are returned as epochs.

----
col1=region&op1=IN&val1=midwest&val1=south&val1=northeast&col2=date&op2=BET&val2=<epoch_start>&val2=<epoch_end>
----
[NOTE]
====
If the Liveboard or Answer you're filtering already has one or more filters applied, the runtime filters will act as an `AND` condition. This means that the data returned must meet the conditions of all filters; those supplied in the runtime filter and those included in the Liveboard or visualization itself.
====

== Limitations of runtime filters

* Runtime filter on `DATE` or `DATE_TIME` must be specified in EPOCH time (Unix or POSIX time).
* Runtime filters do not work directly on top of tables. You must create a Worksheet if you want to use runtime filters. This means that the Liveboard or visualization on which you apply a runtime filter must be created on top of a Worksheet.
* If the Worksheet was created from an Answer (it is an aggregated Worksheet), runtime filters will only work if the Answer was formed using a single Worksheet. If the Answer from which the Worksheet was created includes raw tables or joins multiple worksheets, you won't be able to use runtime filters on it. This is because of the join path ambiguity that could result.
* Runtime filters do not allow you to apply `HAVING` filters in the URL parameters.
* You cannot apply a runtime filter on a Liveboard or visualization built from tables and worksheets that have chasm traps.

////
