= Runtime Parameter overrides
:toc: true
:toclevels: 2

:page-title: Runtime Parameters
:page-pageid: runtime-params
:page-description: Use Parameters to run multiple scenarios with adjustable values, without changing your answer.

ThoughtSpot lets you create Parameters in a Worksheet and integrate them into formulas, filters, data queries, and Liveboards. Parameters are useful for 'what-if' analysis, financial planning, cohort analysis, and so on. Parameters allow users to visualize data by running different scenarios with adjustable values. With Parameters, a single report can be created that a business user adjusts to fit the scenario they want to analyze.

== How to apply Parameters
You can use Parameters within formulas when querying your data via search, Liveboards, or Answers.  For more information about creating and applying Parameters, see the following articles in ThoughtSpot product documentation.

* link:https://docs.thoughtspot.com/cloud/latest/parameters-use[Using Parameters, window=_blank]
* link:https://docs.thoughtspot.com/cloud/latest/parameters-create[Creating Parameters, window=_blank]

== Parameter overrides

You can apply overrides to Parameter values at runtime and visualize data with the adjusted values. Like runtime filters, you can append the Parameters to the end of the URL to modify the resulting output.

To apply overrides to a Liveboard or Answer object, Parameters must be defined in the Worksheet from which the data is retrieved for live analytics.

For example, if you want to override the value of the inflation Parameter on a Liveboard or Answer, add the Parameters to the object URL as shown in these examples:

.Liveboard
----
https://{ThoughtSpot-host}/?param1=Discount&paramVal1=0.25#/pinboard/d084c256-e284-4fc4-b80c-111cb606449a
----

----
https://{ThoughtSpot-host}/#/pinboard/d084c256-e284-4fc4-b80c-111cb606449a?param1=Discount&paramVal1=0.25
----

.Saved Answer
----
https://{ThoughtSpot-host}/?param1=Discount&paramVal1=0.25#/saved-answer/3e84d95c-986e-4154-8362-3807906dad50
----

.Search data
----
https://{ThoughtSpot-host}/?param1=Discount&paramVal1=0.25#/answer/
----

=== Apply Parameter overrides via REST API

To apply overrides to a Liveboard via REST API, add Parameters to the Liveboard data API request URL as shown in the example here:

----
https://{ThoughtSpot-host}/callosum/v1/tspublic/v1/pinboarddata?id=e36ee65e-64be-436b-a29a-22d8998c4fae&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT&param1=Inflation&paramVal1=0.03%2324
----

To apply overrides to an Answer, add Parameters to the search data API request URL as shown here:
----
https://{ThoughtSpot-host}/callosum/v1/tspublic/v1/searchdata?batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT&param1=Inflation&paramVal1=0.03%2324
----

[IMPORTANT]
====
REST API v2.0 endpoints do not support applying runtime Parameter overrides in API requests.
====

=== Add additional Parameters

You can add additional Parameters in the URL by incrementing the number for each Parameter attribute, for example, param1, param2, paramVal1, paramVal2, and so on. To add additional overrides, specify the values by separating them with an ampersand (&) as shown in the examples here:

----
https://{ThoughtSpot-host}/?param1=double%20list%20param&paramVal1=0&param2=double%20param&paramVal2=0#/pinboard/d084c256-e284-4fc4-b80c-111cb606449a
----

----
https://{ThoughtSpot-host}/callosum/v1/tspublic/v1/pinboarddata?id=e36ee65e-64be-436b-a29a-22d8998c4fae&batchsize=-1&pagenumber=-1&offset=-1&formattype=COMPACT&param1=double%20list%20param&paramVal1=0&param2=double%20param&paramVal2=0
----

=== Apply Parameter overrides using Visual Embed SDK

In the current release, the Visual Embed SDK does not support applying runtime Parameter overrides.