= Update cluster state
:toc: true
:toclevels: 1

:page-title: Update cluster state
:page-pageid: tse-dynamic-sense-cluster
:page-description:  If you are using a ThoughtSpot Cloud cluster econoly mode for you embedded applications, use the APIs to restart an inactive cluster.

If you are using a ThoughtSpot Cloud cluster in embedded deployments in your development or production environment, you can enable dynamic idle sensing to save costs and allow your cluster to operate in the `economy` mode. To enable this feature on your clusters, contact ThoughtSpot Support.

== Idle sensing and cluster states
If idle sensing is enabled on your cluster, your cluster will be automatically stopped if there is no user activity detected for a given time threshold. By default, the idle time threshold is set to 120 minutes.

At any given time, a ThoughtSpot cluster can be in any one of the following states:

* `ACTIVE` +
Indicates that the cluster is active and user activity is detected.
* `UNDER_MAINTENANCE` +
Indicates that the cluster is down for maintenance due to upgrade or patching.
* `STOPPED`
Indicates that the cluster is stopped and no user activity is detected.
* `STARTING`/`PENDING` +
Cluster is currently starting, or some other workflow is running on the cluster.

== Update cluster status using APIs
On a regular ThoughtSpot Cloud cluster, users can restart an inactive cluster using `CAPTCHA`. However, on embedded instances, the `CAPTCHA`-based cluster activation is not supported. Instead, the embedded  application user can send a `GET` request to their instance with the following query parameters in the request URL:

* `tse=true`
* `start_cluster=true`

For example, to start an inactive cluster, send a `GET` request in the following parameters:

.Production environment
[source,http]
----
https://<cluster-name>.thoughtspot.cloud/?tse=true&start_cluster=true
----

.Staging environment

[source,http]
----
https://<cluster-name>.thoughtspotstaging.cloud/?tse=true&start_cluster=true
----

.Development environment

[source,http]
----
https://<cluster-name>.thoughtspotdev.cloud/?tse=true&start_cluster=true
----

In the request header, you must also pass the `secret-key` as `Auth-Token`. The `secret_key` is used for authenticating users and is generated when xref:trusted-authentication.adoc#_trusted_authentication[trusted authentication is enabled] on a ThoughtSpot instance. Embedded application users can obtain the `secret key` from their ThoughtSpot administrator.

<Add example -TBD>

If the `GET` request is successful, the API returns the 200 response code with the application details in the response body, and the cluster starts.

== Response header
Note the cluster state in the response header:

* `STARTING` +
Indicates that the cluster is starting.
* `UNKNOWN` +
Indicates a possible error. Contact your administrator or ThoughtSpot Support if the cluster does not start in 5-10 minutes.

== Response codes
[options="header", cols="1,4"]
|===
|HTTP status code|Description
|**200**|Successful operation
|**400**|Invalid request
|**401**|Unauthorized access
|===
