= Version control with Git integration
:toc: true
:toclevels: 2

:page-title: Version control and Git integration for deployments
:page-pageid: git-integration
:page-description: The version control APIs and Git integration capability let you connect your ThoughtSpot instance to a Git repository, push changes, and deploy commits to your ThoughtSpot environment.

When embedding and deploying a third-party application in their apps, most organizations use defined practices through the development, testing, and deployment stages of their SDLC process. Developers typically use a version control system and CI-CD pipelines to push their code through several stages before publishing their application content. ThoughtSpot deployments may require you to publish content from a development environment to a staging or production cluster.

ThoughtSpot objects such as Tables, Worksheets, Liveboards, and Answers are stored in link:https://cloud-docs.thoughtspot.com/admin/ts-cloud/tml.html[ThoughtSpot Modeling Language (TML), window=_blank] and can be downloaded as TML files to your local environment. With the Git integration [beta betaBackground]^Beta^ feature, ThoughtSpot provides the ability to integrate your application environment with a Git repository and push content in the form of TML files to CI/CD pipelines.

== Git integration overview

The Git integration [beta betaBackground]^Beta^ feature supports the following capabilities:

* ThoughtSpot integration with Git and CI/CD workflows
+
Ability to connect your ThoughtSpot instance to a Git repository and deploy commits via REST API.
* Ability to version control ThoughtSpot content
+
Ability to build or modify your content locally on a development instance and push commits to a remote Git branch via APIs and version your updates.

* Ability to address different types of deployment scenarios
+
The simplest deployment scenario is moving content from a ThoughtSpot development instance to a production instance. You can also deploy multiple environments on the same ThoughtSpot instance using the xref:orgs.adoc[Orgs] feature. For example, you can create separate Orgs for `Dev`, `Staging`, and `Prod` environments. The content built from the `Dev` Org can be deployed on `Staging` and `Prod` Orgs using REST API v2.0 version control endpoints.

== How it works

The ThoughtSpot content deployment process with version control APIs and Git integration includes the following steps:

1. xref:version_control.adoc#_enable_git_integration[Enable Git integration on ThoughtSpot].
2. xref:version_control.adoc#connectTS[Connect your ThoughtSpot `Dev` and `Prod` environments to the `dev` and `production` branches on your Git repository]. +
The general practice is to use the `main` branch in your Git repository as a production branch to publish the release content.
3. xref:version_control.adoc#_build_data_objects_on_the_dev_environment[Build and update the objects in your ThoughtSpot `Dev` environment]. +
ThoughtSpot users with edit access to the objects can modify their Liveboard, Answers, Worksheets, and Tables.
4. xref:version_control.adoc#_commit_tml_files_to_git[Push your changes to the Git branch mapped to the `Dev` environment]. +
To push content and deploy commits via REST API, you need administration privileges.
5. On the Git repository, xref:version_control.adoc#_merge_updates_from_dev_branch_to_main_in_git[create a pull request to merge your changes from the `dev` branch to `main` (production branch)].
6. xref:version_control.adoc[Apply commits from the `main` branch to your `Prod` environment] and deploy your content.

The following figure illustrates a simple Git integration workflow with ThoughtSpot `Dev` and `Prod` environments.

image::./images/git-integration-workflow.svg[Git integration workflow]

== Get started

Before getting started, check the following:

* You require administrator access to ThoughtSpot (*Can administer ThoughtSpot* privilege)
* You have a Git repository. If using GitHub, make sure you have a valid account and an access token to connect ThoughtSpot to GitHub. For information about generating a token, see link:https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens[GitHub Documentation, window=_blank].
+
The access token must allow the following scopes:

** `repo:status` +
Access to commit status
** `repo_deployment` +
Access to deployment status
** `public_repo` +
Access to public repositories
** `repo:invite`
Access to repository invitations
** `security_events` +
Read and write security events
* Create a branch in the Git repository that can be used as a default branch.

=== Enable Git integration
To get started with Git integration, enable the Git integration feature on your ThoughtSpot `Dev` and `Prod` environments. If Git integration is not enabled on their instance, administrators must run the following `tscli` command in the 9.3.0.cl release version.

[source,SSH]
----
tscli git-integration enable
----

[#connectTS]
=== Connect your ThoughtSpot environment to Git repository

To connect your ThoughtSpot instance to a Git repository using REST API, send a `POST` request with the following parameters to the `/api/rest/2.0/vcs/git/config/create` REST API v2.0 endpoint.

==== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Parameter|Description
|`repository_url`|__String__. URL of the Git repository.
|`username`
|__String__. Username to authenticate to the Git repository.
|`access_token`|__String__. Access token to authenticate to the Git repository.
|`default_branch_name` +
__Optional__|__String__. Specify the default Git branch used for all operations on the cluster.
|===

==== Request example

The following example shows the API request format for connecting ThoughtSpot to a GitHub repository.

[source, cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/vcs/git/config/create' \
  -H 'Authorization: Bearer {Bearer_token}  \
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "repository_url": "https://github.com/ts-git-user/gitdemo",
  "username": "ts-git-user",
  "access_token": "{ACCESS_TOKEN}",
  "default_branch_name": "dev"
}'
----

If the API request is successful, the ThoughtSpot instance will be connected to the Git repository. Make sure you connect all your environments (`Dev`, `Staging`, and `Prod`) to the GitHub repository.

* To edit the repository details, send a `POST` request with Git configuration parameters to the `/api/rest/2.0/vcs/git/config/update` API endpoint.
* To get repository configuration information, send a `POST` request to `/api/rest/2.0/vcs/git/config/search` API endpoint.
* To delete the repository configuration, send a `POST` request to the `/api/rest/2.0/vcs/git/config/delete` endpoint.

For more information about these endpoints, see the API documentation in the +++<a href="{{previewPrefix}}/api/rest/playgroundV2" target="_blank">REST API v2.0 Playground</a>+++.

=== Build data objects on the Dev environment

Your application users can create and modify their Liveboards, Answers, Connections, Worksheets, and Tables. These objects are stored as TML representations in ThoughtSpot. Users with data management (*Can manage data*) privilege can download these objects as TML files to their local environment, xref:modify-tml.adoc[edit TML files], and import them into ThoughtSpot via UI or REST API. Administrators can push the TML files from a ThoughtSpot instance to the default Git branch using REST API.

==== GUID mapping

Every object in ThoughtSpot has a *GUID* as a unique reference. In the 9.3.0.cl release, GUID mapping is not supported when committing your files to Git. You must manually track the newly created object GUIDs from the destination environment into a GUID mapping file along with the GUID of the source object.

The following example shows a simple mapping of object GUIDs in JSON format:

[source,json]
----
{
  "test": {
    "<dev-env-guid>" :  "<test-env-guid>"
  },
  "staging": {
    "<dev-env-guid>" :  "<staging-env-guid>"
  },
  "prod": {
    "<dev-env-guid>" :  "<prod-env-guid>"
  }
  ...
}
----

When xref:version_control.adoc#_deploy_commits[publishing content to another environment], you *must* swap out the GUIDs from the source environment with those of the equivalent objects in the destination environment within the TML files, so that only the destination environment content is referenced.

=== Commit TML files to Git

To commit the updates to a branch in Git repository via REST API, you need administrator (*Can administer ThoughtSpot*) privilege.

To commit TML objects to a branch in Git, send a `POST` request with the following parameters to the `/api/rest/2.0/vcs/git/branches/commit` API endpoint.

==== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Parameter|Description
|`metadata`|__Array of Strings__. Specify the `type` and GUID of the metadata object.
|`branch_name` +
__Optional__|__String__. Name of the branch in the Git repository to which you want to push.
|`comment`|__String__. Add a comment to the commit.
|===

==== Request example

The following example shows the API request with Liveboard and Worksheet objects to commit to Git.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/vcs/git/branches/commit' \
  -H 'Authorization: Bearer {Bearer_token}\
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "metadata": [
    {
      "identifier": "e9d54c69-d2c1-446d-9529-544759427075",
      "type": "LIVEBOARD"
    },
    {
      "identifier": "cd252e5c-b552-49a8-821d-3eadaa049cca",
      "type": "LOGICAL_TABLE"
    }
  ],
  "comment": "Add objects",
  "branch_name": "dev"
}'
----

If the API request is successful, the objects will be added to the specified GitHub branch. When the TML objects are added to a Git branch, subsequent commits to that branch from ThoughtSpot update the objects in the Git repository.

When committing, if there are no changes detected between the current version in Git, and the version being committed from the ThoughtSpot instance, the API call will succeed, but a warning message is returned with a list of objects that were not updated as part of the commit.

ThoughtSpot provides a REST API endpoint to search commits for a given TML object. A `POST` call to the `/api/rest/2.0/vcs/git/commits/search` endpoint with `metadata` identifier and `type` in the request body fetches a list of commits.

==== Steps to revert a commit
At any point, if you want to revert a commit and return to an earlier version of an object, make a `POST` request to the `/v2/vcs/commits/{commit_id}/revert` API endpoint.

===== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Parameter|Description
|`commit_id`|__String__. Commit ID to which the object should be reverted.
|`metadata` +
__Optional__|__Array of Strings__. Specify the `type` and GUID of the metadata object. If a metadata object is not specified, the API request reverts all objects that were modified as part of the specified `commit_id`.
|`branch_name` +
__Optional__|__String__. Name of the branch to which the revert operation must be applied. If you do not specify the branch name, the API will revert the commit to the default branch configured on that ThoughtSpot instance.
|`revert_policy` a|__String__. Action to apply when reverting a commit. The allowed values are: +

* `ALL_OR_NONE`
Reverts all objects. If the revert operation for one of the objects provided in the commit fails, the API will respond with an error message, and none of the objects will be reverted.
* `PARTIAL`
Reverts partial objects.
|===

==== Request example

The following example shows the API request with Liveboard and Worksheet objects to commit to Git.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/vcs/git/commits/afc0fea831558e30d7064ab019f49243b1f09552/revert' \
  -H 'Authorization: Bearer {Bearer_token}\\
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "metadata": [
    {
      "identifier": "e9d54c69-d2c1-446d-9529-544759427075",
      "type": "LIVEBOARD"
    }
  ],
  "commit_id": "afc0fea831558e30d7064ab019f49243b1f09552",
  "branch_name": "dev"
}'
----

If the API request is successful, the Git branch and the TML object in the ThoughtSpot instance are reverted to the specified commit.

=== Merge updates from `dev` branch to `main` in Git

To merge updates, create a pull request to push changes from your `dev` branch to `main`. ThoughtSpot doesn't provide REST APIs to merge content from one branch to another. Before accepting the merge request in the Git repository, you can validate the merge on your ThoughtSpot instance using REST API.

To validate the merge, send a `POST` request with the following parameters to the `/api/rest/2.0/vcs/git/branches/validate` endpoint:

==== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Parameter|Description
|`source_branch_name`|__String__. Name of the source branch from which changes need to be picked for validation.
|`target_branch_name`|__String__. Name of the target branch into which the TML changes will be merged.
|===

==== Request example

The following example shows the API request with Liveboard and Worksheet objects to commit to Git.

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/vcs/git/branches/validate' \
  -H 'Authorization: Bearer {Bearer_token}\
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "source_branch_name": "dev",
  "target_branch_name": "main"
}'
----

After validating the merge, check for conflicts. Resolve issues if any with a new commit and merge your changes to the `main` branch.

=== Deploy commits

To deploy commits to the `Staging` or `Prod` instance, send a `POST` request to the `/api/rest/2.0/vcs/git/commits/deploy` API endpoint. By default, the API request will deploy the latest version of all changed objects in the default branch to your cluster.

Building a release version for a `Prod` environment on the same instance requires swapping in the correct GUIDs. Because the presence of the *guid* property determines whether an individual TML file will cause a create or update action, you need to keep a *GUID mapping file* to determine how to adjust the TML files for upload to the new environment.

Make sure the  *guid mapping file* is referenced when creating the final TML files for production rollout.

==== Request parameters
[width="100%" cols="1,4"]
[options='header']
|===
|Parameter|Description
|`commit_id` +
__Optional__|__String__. ID of the commit to deploy on the cluster. By default, the command will deploy the latest version of the branch. To deploy a specific version, specify the `commit_id` that should be used.
|`branch_name` +
__Optional__|__String__. Name of the branch from the changes must be deployed. If you do not specify the branch name, the commit from the default branch is deployed.
|`import_type` a|__String__. Specify one of the following options: +

* `DELTA` +
By default, the delta changes between the latest commit of the default branch on the `Prod` instance and the version on the ThoughtSpot instance are applied.
* `FULL` +
To deploy the latest version of all objects from the Git `main` branch to the cluster, specify `FULL`. This will apply all the changes from previous commits.
|`deploy_type` a| __String__. Specify one of the following options: +

* `DELTA` +
Deploys only the modified files at the specified commit.
* `FULL` +
Deploys all files at the specified commit.

|`deploy_policy` a|__String__. Action to apply when deploying a commit. The allowed values are: +

* `ALL_OR_NONE`
Deploys all or none. The `ALL_OR_NONE` option cancels the deployment of all ThoughtSpot objects if at least one of them fails to import.
* `PARTIAL`
Reverts partial objects. Use “Partial” to import ThoughtSpot objects that validate successfully even if other objects in the same deploy operations fail to import.
|===

==== Request example

[source,cURL]
----
curl -X POST \
  --url 'https://{ThoughtSpot-Host}/api/rest/2.0/vcs/git/commits/deploy' \
  -H 'Authorization: Bearer {Bearer_token}'\
  -H 'Accept: application/json'\
  -H 'Content-Type: application/json' \
  --data-raw '{
  "import_type": "DELTA",
  "deploy_type": "DELTA",
  "deploy_policy": "ALL_OR_NONE",
  "commit_id": "afc0fea831558e30d7064ab019f49243b1f09552",
  "branch_name": "main"
}'
----

If the API request is successful, the changes are applied to the objects in the `prod` environment.